name: CI readme

on:

  push:
    branches: 
      - master
  schedule:
   - cron: "0 */6 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0  

      - name: Create README.md
        uses: actions-js/profile-readme@master
        with:
          username: echo724
          github_token: ${{ secrets.GITHUB_TOKEN }}
          template: TEMPLATE.md

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          coauthor_email: echo724@users.noreply.github.com
          coauthor_name: Eunchan Cho
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
